services:
  ucrm-nginx:
    container_name: "ucrm-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - ucrm-app
    ports:
      - 80:80
    volumes:
      - ./:/src

  ucrm-app:
    container_name: "ucrm-app"
    build:
      context: ./docker/php
    depends_on:
      - ucrm-mysql
    ports:
      - 5173:5173
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  ucrm-mysql:
    image: mysql:8.0.37
    command: --max_allowed_packet=32505856
    container_name: "ucrm-mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ucrm
    ports:
      - 3306:3306

  ucrm-redis:
    image: redis:alpine
    container_name: "ucrm-redis"
    ports:
      - 16379:6379

